config/routes.rb
Rails.application.routes.draw do

  resources :item, :activity

  root :to => "activity#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_and_belongs_to_many :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :activities
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.save
    redirect_to activity_index_path
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to activity_index_path
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activity_index_path
  end

private
  def activity_params
  params.require(:activity).permit(:name, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/activity/create.html.erb
<h1>Activity#create</h1>
<p>Find me in app/views/activity/create.html.erb</p>

app/views/activity/destroy.html.erb
<h1>Activity#destroy</h1>
<p>Find me in app/views/activity/destroy.html.erb</p>

app/views/activity/edit.html.erb
<div class="text-center">
<h1>Edit activity <%= @activity.name %></h1>
</div>
<%= simple_form_for @activity do |f| %>
<div class="container shadow bg-white rounded my-5 p-4">
<div class="row">
<div class="col-8">
<%= f.input :name %>
</div>
</div>
<%= f.input :content %>
<div class="text-right">
<%= f.button :submit, class: "btn btn-primary" %>
</div>
</div>
<% end %>

app/views/activity/index.html.erb
<div class="text-center">
<h1>Liste des activités</h1>
</div>
<div class="container">
<div class="row">
<% @activities.each do |activity| %>
<div class="col-12">
<div class="shadow bg-white rounded p-4 d-flex justify-content-between">
<h2><%= activity.name %></h2>
<p><b><%= activity.content %></b></p>

</div>
</div>
<% end %>
<%=link_to "editer acti", edit_activity_path(@activity.id) %>

</div>
</div>

app/views/activity/new.html.erb
<div class="text-center">
<h1>Créé une nouvelle activité</h1>
</div>
<%= simple_form_for @activity do |f| %>
<div class="container shadow bg-white rounded my-5 p-4">
<div class="row">
<div class="col-8">
<%= f.input :name %>
</div>
</div>
<%= f.input :content %>
<div class="text-right">
<%= f.button :submit, class: "btn btn-primary" %>
</div>
</div>

<% end %>

app/views/activity/show.html.erb
<div class="container shadow bg-white rounded p-4 text-center my-5 mb-4">
    <h1><%= @activity.name %></h1>
      <p><%= @activity.content %></p>
          <%= link_to "Supprimer", activity_path(@activity.id), method: :delete, class: "btn btn-danger" %>
          <%= link_to "Modifier", edit_activity_path(@activity.id), class: "btn btn-primary" %>
</div>

app/views/activity/update.html.erb
<h1>Activity#update</h1>
<p>Find me in app/views/activity/update.html.erb</p>

app/views/item/create.html.erb
<h1>Item#create</h1>
<p>Find me in app/views/item/create.html.erb</p>

app/views/item/destroy.html.erb
<h1>Item#destroy</h1>
<p>Find me in app/views/item/destroy.html.erb</p>

app/views/item/edit.html.erb
<h1>Item#edit</h1>
<p>Find me in app/views/item/edit.html.erb</p>

app/views/item/index.html.erb
<h1>Item#index</h1>
<p>Find me in app/views/item/index.html.erb</p>

app/views/item/new.html.erb
<h1>Item#new</h1>
<p>Find me in app/views/item/new.html.erb</p>

app/views/item/show.html.erb
<h1>Item#show</h1>
<p>Find me in app/views/item/show.html.erb</p>

app/views/item/update.html.erb
<h1>Item#update</h1>
<p>Find me in app/views/item/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listepensebete</title>
    <%= csrf_meta_tags %>

    <!-- bootstrap -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
      <!-- end bootstrap -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>